/*
 * O Visão mostrar os dados, para visualizar
 */
package View;

import Controle.ConectaBanco;
import Controle.ControleFornecedor;
import Controle.ModeloTabela;
import Model.ModeloFornecedor;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Mr-Robot
 */
public class JFrFornecedor extends javax.swing.JFrame {
    //Instancia de conexão com o banco = connFornecedor
    ConectaBanco connFornecedor = new ConectaBanco();
    //Instancia de modelo dos dados a fornecer= mod
    ModeloFornecedor mod = new ModeloFornecedor();
    //Instancia de controles dos dados a fornecer = control
    ControleFornecedor control = new ControleFornecedor();
    int mudar = 1;
    /**
     * Creates new form JFrFornecedor
     */
    public JFrFornecedor() {
        initComponents();
        try {
            MaskFormatter form = new MaskFormatter("##.###.###/####-##");//elemento que cria o formato da mascara
            jFormattedTextFieldCNPJ.setFormatterFactory(new DefaultFormatterFactory(form));//atribui a mascara ao campo
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o Numero!\n ERRO: "+ex);
        }
        preencherCombo();
        connFornecedor.conexao();
        preencherTabela("select * from fornecedores inner join bairros on fornecedores.id_bairro = bairros.id_bairro inner join cidades on bairros.id_cidade = cidades.id_cidade inner join estados on cidades.id_estado = estados.id_estado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jComboBoxBairro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelCid = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedor");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Cadastro de Fornecedor");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("Bairro:");

        jTextFieldID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldID.setEnabled(false);

        jTextFieldEndereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEndereco.setEnabled(false);

        jComboBoxBairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxBairroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxBairroMouseEntered(evt);
            }
        });

        jLabel5.setText("Nome:");

        jTextFieldNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNome.setEnabled(false);

        jLabel6.setText("CNPJ:");

        jLabelCid.setText("Cidade:");

        jLabelCidade.setText("Nome");

        jLabelEstado.setText("Estado");

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonPrimeiro.setText("<<");
        jButtonPrimeiro.setToolTipText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("<");
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setText(">");
        jButtonProximo.setToolTipText("Proximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonUltimo.setText(">>");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jFormattedTextFieldCNPJ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldCNPJ.setEnabled(false);

        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableFornecedor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(52, 52, 52)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabelCid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jButtonNovo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPrimeiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAnterior)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonProximo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonUltimo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSair)
                                    .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidade)
                    .addComponent(jLabelEstado)
                    .addComponent(jLabelCid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(347, 347, 347))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(979, 644));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        //habilita os textFilds com = true
        jTextFieldNome.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jFormattedTextFieldCNPJ.setEnabled(true);
        //habilita os botões com = true
        jButtonSalvar.setEnabled(true);
        //desabilita os botões com = false
        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        //Utiizando logica de programação
        // ser for 1 salver os dados 
        if( mudar == 1){
            mod.setNome(jTextFieldNome.getText());
            mod.setEndereco(jTextFieldEndereco.getText());
            mod.setCNPJ(jFormattedTextFieldCNPJ.getText());
            //faz a conversão para String e joga na comboBox
            mod.setIdBairro((String)jComboBoxBairro.getSelectedItem());
            control.Salvar(mod);
            //habilita os textFilds com = !true serve para inversão da chamada
            jTextFieldNome.setEnabled(!true);
            jTextFieldEndereco.setEnabled(!true);
            jFormattedTextFieldCNPJ.setEnabled(!true);
            jTextFieldID.setText("");
            jTextFieldNome.setText("");
            jTextFieldEndereco.setText("");
            jFormattedTextFieldCNPJ.setText("");
            //habilita os botões com = !true
            jButtonSalvar.setEnabled(!true);
            //desabilita os botões com = !false
            jButtonNovo.setEnabled(!false);
            preencherTabela("select * from fornecedores");
        // Caso aucontrario altere os dados
        } else{
            mod.setNome(jTextFieldNome.getText());
            mod.setEndereco(jTextFieldEndereco.getText());
            mod.setCNPJ(jFormattedTextFieldCNPJ.getText());
            //faz a conversão para String e joga na comboBox
            mod.setIdBairro((String)jComboBoxBairro.getSelectedItem());
            control.Alterar(mod);
            //habilita os textFilds com = !true serve para inversão da chamada
            jTextFieldNome.setEnabled(!true);
            jTextFieldEndereco.setEnabled(!true);
            jFormattedTextFieldCNPJ.setEnabled(!true);
            jTextFieldID.setText("");
            jTextFieldNome.setText("");
            jTextFieldEndereco.setText("");
            jFormattedTextFieldCNPJ.setText("");
            //habilita os botões com = !true
            jButtonSalvar.setEnabled(!true);
            //desabilita os botões com = !false
            jButtonNovo.setEnabled(!false);
            preencherTabela("select * from fornecedores");
            //Codigo de verificação ser esta funcionando
            //JOptionPane.showMessageDialog(rootPane, "Alterar");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        //pegando os dados dos campos, que foi digitado
        mod.setNome(jTextFieldNome.getText());
        mod.setEndereco(jTextFieldEndereco.getText());
        mod.setCNPJ(jFormattedTextFieldCNPJ.getText());
        //faz a conversão para String e joga na comboBox
        mod.setIdBairro((String)jComboBoxBairro.getSelectedItem());
        mudar = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jFormattedTextFieldCNPJ.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        mod.setNome(jTextFieldNome.getText());
        mod.setEndereco(jTextFieldEndereco.getText());
        mod.setCNPJ(jFormattedTextFieldCNPJ.getText());
        //faz a conversão para String e joga na comboBox
        mod.setIdBairro((String)jComboBoxBairro.getSelectedItem());
        control.Excluir(mod);
        //habilita os textFilds com = !true serve para inversão da chamada
        jTextFieldNome.setEnabled(!true);
        jTextFieldEndereco.setEnabled(!true);
        jFormattedTextFieldCNPJ.setEnabled(!true);
        jTextFieldID.setText("");
        jTextFieldNome.setText("");
        jTextFieldEndereco.setText("");
        jFormattedTextFieldCNPJ.setText("");
        //habilita os botões com = !true = como forma de negação,que true é igual a false, e false é igual a true
        jButtonSalvar.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        //desabilita os botões com = !false
        jButtonNovo.setEnabled(!false);
         preencherTabela("select * from fornecedores");
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        mod = control.Primeiro();
        jTextFieldID.setText(""+mod.getId());
        jTextFieldNome.setText(mod.getNome());
        jTextFieldEndereco.setText(mod.getEndereco());
        jFormattedTextFieldCNPJ.setText(mod.getCNPJ());
        jComboBoxBairro.setSelectedItem(mod.getIdBairro());
        jLabelCidade.setText(mod.getNome_Cidade());
        jLabelEstado.setText(mod.getSigla_estado());
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        mod = control.Anterior();
        jTextFieldID.setText(""+mod.getId());
        jTextFieldNome.setText(mod.getNome());
        jTextFieldEndereco.setText(mod.getEndereco());
        jFormattedTextFieldCNPJ.setText(mod.getCNPJ());
        jComboBoxBairro.setSelectedItem(mod.getIdBairro());
        jLabelCidade.setText(mod.getNome_Cidade());
        jLabelEstado.setText(mod.getSigla_estado());
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        mod = control.Proximo();
        jTextFieldID.setText(""+mod.getId());
        jTextFieldNome.setText(mod.getNome());
        jTextFieldEndereco.setText(mod.getEndereco());
        jFormattedTextFieldCNPJ.setText(mod.getCNPJ());
        jComboBoxBairro.setSelectedItem(mod.getIdBairro());
        jLabelCidade.setText(mod.getNome_Cidade());
        jLabelEstado.setText(mod.getSigla_estado());
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        mod = control.Ultimo();
        jTextFieldID.setText(""+mod.getId());
        jTextFieldNome.setText(mod.getNome());
        jTextFieldEndereco.setText(mod.getEndereco());
        jFormattedTextFieldCNPJ.setText(mod.getCNPJ());
        jComboBoxBairro.setSelectedItem(mod.getIdBairro());
        jLabelCidade.setText(mod.getNome_Cidade());
        jLabelEstado.setText(mod.getSigla_estado());
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        //saindo da interface
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jComboBoxBairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBairroMouseClicked
        /*try {
            connFornecedor.conexao();
            //selecionados todas as tabela , e cria uma nova tabela com o join que mostras os resultados
            connFornecedor.executaSQL("select * from bairros inner join cidades on bairros.id_cidade = cidades.id_cidade inner join estados on cidades.id_estado = estados.id_estado where nome_bairro = '"+jComboBoxBairro.getSelectedItem()+"'");
            connFornecedor.rs.first();
            jLabelCidade.setText(connFornecedor.rs.getString("nome_cidades"));
            jLabelEstado.setText(connFornecedor.rs.getString("sigla_estado"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao selecionar o Bairro!\nERRO: "+ex);
        }
        //connFornecedor.desconecta();*/
    }//GEN-LAST:event_jComboBoxBairroMouseClicked

    private void jComboBoxBairroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBairroMouseEntered
       try {
            connFornecedor.conexao();
            //selecionados todas as tabela , e cria uma nova tabela com o join que mostras os resultados
            connFornecedor.executaSQL("select * from bairros inner join cidades on bairros.id_cidade = cidades.id_cidade inner join estados on cidades.id_estado = estados.id_estado where nome_bairro='"+jComboBoxBairro.getSelectedItem()+"'");
            connFornecedor.rs.first();
            jLabelCidade.setText(connFornecedor.rs.getString("nome_cidades"));
            jLabelEstado.setText(connFornecedor.rs.getString("sigla_estado"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao selecionar o Bairro!\nERRO: "+ex);
        }
        //connFornecedor.desconecta();                   
    }//GEN-LAST:event_jComboBoxBairroMouseEntered
    //Preenchendo a comboBox com a tabela Bairro
    public void preencherCombo(){
        //conexão com o banco postgres
        connFornecedor.conexao();
        //selecão da tabela banco todos os nnome de bairro
        connFornecedor.executaSQL("select * from bairros order by nome_bairro");
        jComboBoxBairro.removeAllItems();
        try {
            //setando para a primeira posição da chamada
            connFornecedor.rs.first();
            do{
                //preenchendo a comboBox com os dados da tabela Bairro, que veem do banco
                jComboBoxBairro.addItem(""+connFornecedor.rs.getString("nome_bairro"));
            } while(connFornecedor.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preencher os Bairros!\nERRO: "+ex);
        }
        // desconectando o banco
        connFornecedor.desconecta();
    }
    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"ID", "Nomes", "CNPJ", "Cidades", "Estados"};
        
        connFornecedor.executaSQL(SQL);
        try {
            connFornecedor.rs.first();
            //preenchendo a tabela
            do {
                //buscar dados no resultset
                dados.add(new Object[]{connFornecedor.rs.getInt("id_fornecedor"),connFornecedor.rs.getString("nome_fornecedor"),connFornecedor.rs.getString("cnpj_fornecedor"),connFornecedor.rs.getString("nome_cidades"),connFornecedor.rs.getString("sigla_estado")});
                //qtd += +1;
            } while(connFornecedor.rs.next());
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!\n ERRO: "+ex);
        }
        //JOptionPane.showMessageDialog(rootPane, "Quantidade de resgistros:" + qtd);
        //instancia do tabela
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableFornecedor.setModel(modelo);
        jTableFornecedor.getColumnModel().getColumn(0).setPreferredWidth(90);
        jTableFornecedor.getColumnModel().getColumn(0).setResizable(false);
        jTableFornecedor.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTableFornecedor.getColumnModel().getColumn(1).setResizable(false);
        jTableFornecedor.getColumnModel().getColumn(2).setPreferredWidth(210);
        jTableFornecedor.getColumnModel().getColumn(2).setResizable(false);
        jTableFornecedor.getColumnModel().getColumn(3).setPreferredWidth(210);
        jTableFornecedor.getColumnModel().getColumn(3).setResizable(false);
        jTableFornecedor.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTableFornecedor.getColumnModel().getColumn(4).setResizable(false);
        jTableFornecedor.getTableHeader().setReorderingAllowed(false);
        jTableFornecedor.setAutoResizeMode(jTableFornecedor.AUTO_RESIZE_OFF);
        jTableFornecedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JComboBox<String> jComboBoxBairro;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCid;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFornecedor;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
