/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controle.ConectaBanco;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;



/**
 *
 * @author Mr-Robot
 */
public class JFrLogin extends javax.swing.JFrame {

    ConectaBanco connLogar = new ConectaBanco();
    /**
     * Creates new form ViewLogin
     */
    public JFrLogin() {
        initComponents();
        //centralizando tela no centro
        setLocationRelativeTo(null);
        connLogar.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelLogin = new javax.swing.JPanel();
        jT_login = new javax.swing.JTextField();
        jPassF_senha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jB_entra = new javax.swing.JButton();
        jB_sair = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Autenticação Sistema de Vendas");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Autenticação");

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("ISSoftware Busines");

        jPanelLogin.setBackground(new java.awt.Color(255, 204, 204));
        jPanelLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jT_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_loginActionPerformed(evt);
            }
        });

        jPassF_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassF_senhaActionPerformed(evt);
            }
        });
        jPassF_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPassF_senhaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Login do sistema");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Senha:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Usuário:");

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPassF_senha)
                            .addComponent(jT_login, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jT_login, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassF_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(55, 55, 55))
        );

        jB_entra.setBackground(new java.awt.Color(0, 204, 51));
        jB_entra.setText("Entrar");
        jB_entra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_entra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_entraActionPerformed(evt);
            }
        });

        jB_sair.setBackground(new java.awt.Color(255, 51, 0));
        jB_sair.setText("Sair");
        jB_sair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sairActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 102));
        jLabel6.setText("SISTEMA DE VENDA");

        jLabel7.setText("Desenvolvedor.: Israel Pereira");

        jLabel8.setText("www.israel206.github.io");

        jLabel9.setText("israelfera2007@gmail.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel2)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB_entra, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jB_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_entra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_sair))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_entraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_entraActionPerformed
        try {
            // TODO add your handling code here:
            //permissões para os formularios
            connLogar.executaSQL("select * from login where login='"+jT_login.getText()+"'" );
            connLogar.rs.first();
            if(connLogar.rs.getString("senha_login").equals(jPassF_senha.getText())){
                
                //teste de login desenvolvedor
                if(connLogar.rs.getString("permissao").equals("Desenvolvedor")){
                    View.Principal frm = new View.Principal(jT_login.getText());//passando a string princpal
                    frm.setVisible(true);
                }else{
                    connLogar.executaSQL("select * from vencimento");
                    connLogar.rs.last();

                    SimpleDateFormat df = new SimpleDateFormat("ddMMyyyy");
                    Date hoje = new Date();

                    String dataAtual = df.format(hoje);

                    String dataSistema = connLogar.rs.getString("datavenc");

                    int diaAt, mesAt, anoAt, diaVenc, mesVenc, anoVenc;

                    //datas atuais
                    diaAt = Integer.parseInt("" + dataAtual.charAt(0) + dataAtual.charAt(1));
                    mesAt = Integer.parseInt("" + dataAtual.charAt(2) + dataAtual.charAt(3));
                    anoAt = Integer.parseInt("" + dataAtual.charAt(4) + dataAtual.charAt(5) + dataAtual.charAt(6) + dataAtual.charAt(7));

                    //datas vencida
                    diaVenc = Integer.parseInt("" + dataSistema.charAt(0) + dataSistema.charAt(1));
                    mesVenc = Integer.parseInt("" + dataSistema.charAt(2) + dataSistema.charAt(3));
                    anoVenc = Integer.parseInt("" + dataSistema.charAt(4) + dataSistema.charAt(5) + dataSistema.charAt(6) + dataSistema.charAt(7));

                    if((diaAt <= diaVenc) && (mesAt <= mesVenc) && (anoAt == anoVenc)){
                        View.Principal frm = new View.Principal(jT_login.getText());//passando a string princpal
                        frm.setVisible(true);
                        dispose();
                    }else{
                        View.JFrValidSistema frm = new View.JFrValidSistema();// chama a tela  de Sistema de validação
                        frm.setVisible(true); 
                    }
                }// teste
            }else{
                JOptionPane.showMessageDialog(rootPane, "O usuário ou a senha não corresponde!");
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "O usuário ou a senha não corresponde!");
        }                                           
    
//    public ModeloLogin autentica(ModeloLogin mod){
//        String salt = getSaltLogin(mod.getLogin());
//        
//        return(ModeloLogin) criteria.uniqueResult();
//    }
//    private ModeloLogin getSaltLogin(ModeloLogin mod){
//    
//        return salt;
//    }
    }//GEN-LAST:event_jB_entraActionPerformed

    private void jB_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jB_sairActionPerformed

    private void jT_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_loginActionPerformed
        jPassF_senha.requestFocus();
    }//GEN-LAST:event_jT_loginActionPerformed

    private void jPassF_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassF_senhaActionPerformed
        
    }//GEN-LAST:event_jPassF_senhaActionPerformed

    private void jPassF_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassF_senhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                try {
                // TODO add your handling code here:
                //permissões para os formularios
                connLogar.executaSQL("select * from login where login='"+jT_login.getText()+"'");
                connLogar.rs.first();
                if(connLogar.rs.getString("senha_login").equals(jPassF_senha.getText())){

                    //teste de login desenvolvedor
                    if(connLogar.rs.getString("permissao").equals("Desenvolvedor")){
                        View.Principal frm = new View.Principal(jT_login.getText());//passando a string princpal
                        frm.setVisible(true);
                    }else{
                        connLogar.executaSQL("select * from vencimento");
                        connLogar.rs.last();

                        SimpleDateFormat df = new SimpleDateFormat("ddMMyyyy");
                        Date hoje = new Date();

                        String dataAtual = df.format(hoje);

                        String dataSistema = connLogar.rs.getString("datavenc");

                        int diaAt, mesAt, anoAt, diaVenc, mesVenc, anoVenc;

                        //datas atuais
                        diaAt = Integer.parseInt("" + dataAtual.charAt(0) + dataAtual.charAt(1));
                        mesAt = Integer.parseInt("" + dataAtual.charAt(2) + dataAtual.charAt(3));
                        anoAt = Integer.parseInt("" + dataAtual.charAt(4) + dataAtual.charAt(5) + dataAtual.charAt(6) + dataAtual.charAt(7));

                        //datas vencida
                        diaVenc = Integer.parseInt("" + dataSistema.charAt(0) + dataSistema.charAt(1));
                        mesVenc = Integer.parseInt("" + dataSistema.charAt(2) + dataSistema.charAt(3));
                        anoVenc = Integer.parseInt("" + dataSistema.charAt(4) + dataSistema.charAt(5) + dataSistema.charAt(6) + dataSistema.charAt(7));

                        if((diaAt <= diaVenc) && (mesAt <= mesVenc) && (anoAt == anoVenc)){
                            View.Principal frm = new View.Principal(jT_login.getText());//passando a string princpal
                            frm.setVisible(true);
                            dispose();
                        }else{
                            View.JFrValidSistema frm = new View.JFrValidSistema();// chama a tela  de Sistema de validação
                            frm.setVisible(true); 
                        }
                    }// teste
                }else{
                    JOptionPane.showMessageDialog(rootPane, "O usuário ou a senha não corresponde!");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "O usuário ou a senha não corresponde!");
            }
        }
    }//GEN-LAST:event_jPassF_senhaKeyPressed

//    private void entrar(){
//        
//    }
    
    /**
     * limpar formulário usuário
     */
    private void limparCampos(){
        jT_login.setText("");
        jPassF_senha.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                ////////////////////////PERSONALIZANDO TELA DE VIEW///////COMEÇA O LOOK AQUI///////
                LookAndFeel lf = UIManager.getLookAndFeel();
                
                try {
                    for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (UnsupportedLookAndFeelException exc) {
                } catch (ClassNotFoundException exc){
                } catch (InstantiationException exc){
                } catch (IllegalAccessException exc){
                }
                
                UIManager.put("nimbusBase", new Color(100, 50, 30));
                
                UIManager.put("nimbusBlueGrey", new Color(190, 189, 170));
                
                UIManager.put("control", new Color(242, 242, 242));
                
                ////////////////////////////////////////////////TERMINAR O LOOK AQUI////////////////////
                
                new JFrLogin().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_entra;
    private javax.swing.JButton jB_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPassF_senha;
    private javax.swing.JTextField jT_login;
    // End of variables declaration//GEN-END:variables
}
