/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ConectaBanco;
import Controle.ControleVenda;
import Controle.ModeloTabela;
import Model.ModeloVendas;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Mr-Robot
 */
public class JFrVendas extends javax.swing.JFrame {
    
    ConectaBanco connVendas = new ConectaBanco();
    ModeloVendas modVenda = new ModeloVendas();
    ControleVenda controlVenda = new ControleVenda();
    
    //variaveis global
    int flag = 1, codVenda;
    float preco_produto, total = 0;
    /**
     * Creates new form JFrVendas
     */
    public JFrVendas() {
        initComponents();
//        try {
//            MaskFormatter form = new MaskFormatter("##/##/####");//elemento que cria o formato da mascara data
//            jFormattedTextFieldData.setFormatterFactory(new DefaultFormatterFactory(form));//atribui a mascara ao campo
//        } catch (ParseException ex) {
//            JOptionPane.showMessageDialog(null, "Erro ao preencher o Numero!\n ERRO: " + ex);
//        }
        // Pega data do sistema
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        jFormattedTextFieldData.setText(df.format(hoje));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelCliente = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jButtonBuscaCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jButtonBuscaProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQuantidade_Produto = new javax.swing.JTextField();
        jTextFieldValorItem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableItemVenda = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jButtonFinalizarVenda = new javax.swing.JButton();
        jButtonCancelarVenda = new javax.swing.JButton();
        jButtonAddItens = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxPagamentos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Vendas");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Formulário de Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCliente.setText("Nome do Cliente:");

        jButtonBuscaCliente.setText("Busca");
        jButtonBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Produto:");

        jTextFieldProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoActionPerformed(evt);
            }
        });

        jButtonBuscaProduto.setText("Busca");
        jButtonBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de Compra:");

        jFormattedTextFieldData.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldData.setEnabled(false);
        jFormattedTextFieldData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldDataFocusGained(evt);
            }
        });

        jLabel4.setText("Quantidade Produto:");

        jLabel5.setText("Valor % por item:");

        jTextFieldQuantidade_Produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldQuantidade_ProdutoFocusGained(evt);
            }
        });
        jTextFieldQuantidade_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidade_ProdutoActionPerformed(evt);
            }
        });

        jLabel6.setText("Tabela de Pesquisa:");

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisa);

        jLabel7.setText("Itens da Venda:");

        jTableItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableItemVenda);

        jLabel8.setText("Valor Total:");

        jButtonFinalizarVenda.setText("Finalizar Venda");
        jButtonFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarVendaActionPerformed(evt);
            }
        });

        jButtonCancelarVenda.setText("Cancelar venda");
        jButtonCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarVendaActionPerformed(evt);
            }
        });

        jButtonAddItens.setText("Add");
        jButtonAddItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItensActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        jLabel9.setText("Forma de Pagamento:");

        jComboBoxPagamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A vista", "Parcelado" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscaCliente)))
                                .addGap(54, 54, 54)
                                .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldQuantidade_Produto))
                                        .addGap(91, 91, 91)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(219, 219, 219)
                                                .addComponent(jButtonAddItens, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(422, 422, 422)
                                        .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 198, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscaProduto)
                            .addComponent(Sair))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonFinalizarVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarVenda)
                        .addGap(92, 92, 92))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaCliente)
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidade_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddItens)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sair)
                    .addComponent(jTextFieldValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFinalizarVenda)
                    .addComponent(jButtonCancelarVenda))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(975, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaClienteActionPerformed
        // TODO add your handling code here:
        flag = 1;
        preencherTabelaCliente("select * from clientes where nome_cliente like'%"+jTextFieldCliente.getText()+"%'");
    }//GEN-LAST:event_jButtonBuscaClienteActionPerformed

    private void jButtonBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaProdutoActionPerformed
        // TODO add your handling code here:
        connVendas.conexao();
        PreparedStatement  pst;
        try {
            pst = connVendas.conn.prepareStatement("insert into vendas (valor_venda)values(?)");
            pst.setFloat(1, 0);
            pst.execute();
            connVendas.executaSQL("select * from vendas");
            connVendas.rs.last();
            codVenda = connVendas.rs.getInt("id_venda");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO na busca da venda: " + ex);
        }    
        flag = 2;
        preencherTabelaProduto("select * from produtos where nome_produto like '%"+jTextFieldProduto.getText()+"%'");
        
    }//GEN-LAST:event_jButtonBuscaProdutoActionPerformed

    private void jTablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaMouseClicked
        // TODO add your handling code here:
        if(flag == 1){
            String nome_cliente = ""+jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(), 1);
            jTextFieldCliente.setText(nome_cliente);
        }
        else{
            connVendas.conexao();
            try {
                String nome_produto = ""+jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(), 1);
                connVendas.executaSQL("select * from produtos where nome_produto='"+nome_produto+"'");
                connVendas.rs.first();
                preco_produto = connVendas.rs.getFloat("preco_venda");
                jTextFieldProduto.setText(nome_produto);
                jTextFieldValorItem.setText(String.valueOf(preco_produto));
                jTextFieldQuantidade_Produto.setText("1");
                connVendas.desconecta();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao Pesquisar o preço!");
            }
        }
    }//GEN-LAST:event_jTablePesquisaMouseClicked

    private void jTextFieldQuantidade_ProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQuantidade_ProdutoFocusGained
        // TODO add your handling code here:
        float valorTotal;
        valorTotal = Float.parseFloat(jTextFieldValorItem.getText()) * Integer.parseInt(jTextFieldQuantidade_Produto.getText());
        jTextFieldValorTotal.setText(String.valueOf(valorTotal));
    }//GEN-LAST:event_jTextFieldQuantidade_ProdutoFocusGained

    private void jFormattedTextFieldDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataFocusGained
        // TODO add your handling code here:
        float valorTotal;
        valorTotal = Float.parseFloat(jTextFieldValorItem.getText()) * Integer.parseInt(jTextFieldQuantidade_Produto.getText());
        //jTextFieldValorTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jFormattedTextFieldDataFocusGained

    private void jButtonAddItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItensActionPerformed
        try {
            // TODO add your handling code here:
            int idVenda, quantidade = 0;
            connVendas.conexao();
            connVendas.executaSQL("select * from produtos where nome_produto = '"+jTextFieldProduto.getText()+"'");
            connVendas.rs.first();
            quantidade = connVendas.rs.getInt("quantidade");
            if(quantidade >= Integer.parseInt(jTextFieldQuantidade_Produto.getText())){
               
                modVenda.setNomeProduto(jTextFieldProduto.getText());
                modVenda.setQtdItem(Integer.parseInt(jTextFieldQuantidade_Produto.getText()));
                modVenda.setIdVenda(codVenda);
                controlVenda.adiconaItem(modVenda);
                preencherTabelaItensVendas("select * from produtos inner join itens_venda_produto on produtos.id_produto = itens_venda_produto.id_produto inner join vendas on vendas.id_venda = itens_venda_produto.id_venda where vendas.id_venda =" + codVenda);
            }else{
                JOptionPane.showMessageDialog(rootPane, "A quantidade desejada não está disponivél no estoque!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao pesquisar a quantidade!\nERRO:" + ex);
        }
    }//GEN-LAST:event_jButtonAddItensActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
         dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void jButtonFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarVendaActionPerformed
        // TODO add your handling code here:
        if(jComboBoxPagamentos.getSelectedItem().equals("A vista")){
            modVenda.setIdVenda(codVenda);
            modVenda.setNomeCliente(jTextFieldCliente.getText());
            modVenda.setData(jFormattedTextFieldData.getText());
            modVenda.setValorVenda(Float.parseFloat(jTextFieldValorTotal.getText()));
            modVenda.setPagamento((String)jComboBoxPagamentos.getSelectedItem());
            controlVenda.FechaVenda(modVenda);
            dispose();
        }else{
            modVenda.setIdVenda(codVenda);
            modVenda.setNomeCliente(jTextFieldCliente.getText());
            modVenda.setData(jFormattedTextFieldData.getText());
            modVenda.setValorVenda(Float.parseFloat(jTextFieldValorTotal.getText()));
            modVenda.setPagamento((String)jComboBoxPagamentos.getSelectedItem());
            controlVenda.FechaVenda(modVenda);
            JFrParcelamentoVenda frm = new JFrParcelamentoVenda(codVenda);
            frm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButtonFinalizarVendaActionPerformed

    private void jButtonCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarVendaActionPerformed
        // TODO add your handling code here:
        controlVenda.CancelarVenda();
        dispose();
    }//GEN-LAST:event_jButtonCancelarVendaActionPerformed

    private void jTextFieldProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoActionPerformed

    private void jTextFieldQuantidade_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidade_ProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantidade_ProdutoActionPerformed
    
    public void preencherTabelaCliente(String sql){
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código", "Nome"};
        connVendas.conexao();
        
        try{
            connVendas.executaSQL(sql);
            connVendas.rs.first();
            do {
                dados.add(new Object[]{connVendas.rs.getString("id_cliente"),connVendas.rs.getString("nome_cliente")});
            } while(connVendas.rs.next());
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!\n ERRO: " + ex);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTablePesquisa.setModel(modelo);
        jTablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(316);
        jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisa.getTableHeader().setReorderingAllowed(false);
        jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
        jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    public void preencherTabelaProduto(String sql){
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código", "Nome", "Quantidade"};
        connVendas.conexao();
        
        try{
            connVendas.executaSQL(sql);
            connVendas.rs.first();
            do {
                dados.add(new Object[]{connVendas.rs.getString("id_produto"),connVendas.rs.getString("nome_produto"),connVendas.rs.getString("quantidade")});
            } while(connVendas.rs.next());
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!\n ERRO: " + ex);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTablePesquisa.setModel(modelo);
        jTablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(1).setPreferredWidth(500);
        jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(2).setPreferredWidth(220);
        jTablePesquisa.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisa.getTableHeader().setReorderingAllowed(false);
        jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
        jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void preencherTabelaItensVendas(String sql){
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Descrição", "Quantidade", "Valor Total"};
        connVendas.conexao();
        connVendas.executaSQL(sql);
        try{
            connVendas.rs.first();
            do {
                float valorProduto = connVendas.rs.getFloat("preco_venda");
                int qtdVendida = connVendas.rs.getInt("quantidade_produto");
                dados.add(new Object[]{connVendas.rs.getString("nome_produto"),connVendas.rs.getString("quantidade_produto"),valorProduto * qtdVendida});
            } while(connVendas.rs.next());
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!\n ERRO: " + ex);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableItemVenda.setModel(modelo);
        jTableItemVenda.getColumnModel().getColumn(0).setPreferredWidth(500);
        jTableItemVenda.getColumnModel().getColumn(0).setResizable(false);
        jTableItemVenda.getColumnModel().getColumn(1).setPreferredWidth(170);
        jTableItemVenda.getColumnModel().getColumn(1).setResizable(false);
        jTableItemVenda.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTableItemVenda.getColumnModel().getColumn(2).setResizable(false);
        jTableItemVenda.getTableHeader().setReorderingAllowed(false);
        jTableItemVenda.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
        jTableItemVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        SomaProduto();
    }
    
    public void SomaProduto(){
        total = 0;
        int qtd = 0;
        float valor = 0;
        connVendas.executaSQL("select * from itens_venda_produto inner join produtos on itens_venda_produto.id_produto = produtos.id_produto where id_venda="+ codVenda);
        try {
            //connVendas.rs.first();
            while(connVendas.rs.next()){
                qtd = connVendas.rs.getInt("quantidade");
                valor = connVendas.rs.getFloat("preco_venda");
                total = total + connVendas.rs.getFloat("preco_venda") * connVendas.rs.getInt("quantidade_produto");
                //JOptionPane.showMessageDialog(null, "qtd = " + qtd + " pv = " + valor);
            }
            jTextFieldValorTotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na Somar do total!\n ERRO: " + ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JButton jButtonAddItens;
    private javax.swing.JButton jButtonBuscaCliente;
    private javax.swing.JButton jButtonBuscaProduto;
    private javax.swing.JButton jButtonCancelarVenda;
    private javax.swing.JButton jButtonFinalizarVenda;
    private javax.swing.JComboBox<String> jComboBoxPagamentos;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableItemVenda;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQuantidade_Produto;
    private javax.swing.JTextField jTextFieldValorItem;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables
}
